# Generated by Django 5.0.4 on 2024-06-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonsterputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasKarmtvatt', models.BooleanField(default=False, verbose_name='Karmtvätt')),
                ('hasStegeBehovs', models.BooleanField(default=False, verbose_name='Stege')),
                ('stegeAvgift', models.IntegerField(default=350)),
                ('commentFonster', models.TextField(blank=True, verbose_name='kommentar för fönster')),
                ('totalAmount', models.IntegerField()),
                ('selectedDate', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('selectedTime', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Hemstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bostadsyta', models.CharField(blank=True, max_length=255)),
                ('husdjur', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=50)),
                ('hasKatt', models.BooleanField(default=False, verbose_name='Katt')),
                ('hasHund', models.BooleanField(default=False, verbose_name='Hund')),
                ('hasAnnat', models.BooleanField(default=False, verbose_name='Annat')),
                ('frekvens', models.CharField(choices=[('biweekly', 'biweekly'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='biweekly', max_length=50)),
                ('totalAmount', models.IntegerField()),
                ('selectedDate', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('selectedTime', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Storstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bostadsyta', models.CharField(blank=True, max_length=255)),
                ('husdjur', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=50)),
                ('hasKatt', models.BooleanField(default=False, verbose_name='Katt')),
                ('hasHund', models.BooleanField(default=False, verbose_name='Hund')),
                ('hasAnnat', models.BooleanField(default=False, verbose_name='Annat')),
                ('fonsterputs', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=50)),
                ('hasKarmtvatt', models.BooleanField(default=False, verbose_name='Karmtvätt')),
                ('hasStegeBehovs', models.BooleanField(default=False, verbose_name='Stege')),
                ('hasStadutrustning', models.BooleanField(default=False, verbose_name='Städutrustning')),
                ('ovenCount', models.IntegerField(default=0, verbose_name='Ugnsrengöring')),
                ('fridgeCount', models.IntegerField(default=0, verbose_name='Kylskåpsrengöring')),
                ('comment', models.TextField(blank=True, verbose_name='kommentar')),
                ('commentFonster', models.TextField(blank=True, verbose_name='kommentar för fönster')),
                ('keyStatus', models.CharField(choices=[('atHome', 'atHome'), ('willLeaveOneDayBefore', 'willLeaveOneDayBefore'), ('alreadyLeftKey', 'alreadyLeftKey')], default='atHome', max_length=50)),
                ('utrustningAvgift', models.IntegerField(default=350)),
                ('serviceAvgift', models.IntegerField(default=70)),
                ('stegeAvgift', models.IntegerField(default=350)),
                ('totalAmount', models.IntegerField()),
                ('selectedDate', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('selectedTime', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('gatuAdress', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress')),
                ('postNummer', models.CharField(blank=True, max_length=10, verbose_name='Postnummer')),
                ('postOrt', models.CharField(blank=True, max_length=100, verbose_name='Post Ort')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='flyttochren.storstadning')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoFonsterputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('gatuAdress', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress')),
                ('postNummer', models.CharField(blank=True, max_length=10, verbose_name='Postnummer')),
                ('postOrt', models.CharField(blank=True, max_length=100, verbose_name='Post Ort')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='flyttochren.fonsterputs')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoHemstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('gatuAdress', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress')),
                ('postNummer', models.CharField(blank=True, max_length=10, verbose_name='Postnummer')),
                ('postOrt', models.CharField(blank=True, max_length=100, verbose_name='Post Ort')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='flyttochren.hemstadning')),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utanSprojs_count', models.IntegerField(default=0)),
                ('utanSprojs_sides', models.IntegerField(default=4)),
                ('medSprojs_count', models.IntegerField(default=0)),
                ('medSprojs_sides', models.IntegerField(default=4)),
                ('overhangda_count', models.IntegerField(default=0)),
                ('overhangda_sides', models.IntegerField(default=4)),
                ('balkong_count', models.IntegerField(default=0)),
                ('balkong_sides', models.IntegerField(default=4, verbose_name='Helt eller Endast glasräcke')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='flyttochren.storstadning')),
            ],
        ),
        migrations.CreateModel(
            name='WindowsFonsterputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utanSprojs_count', models.IntegerField(default=0)),
                ('utanSprojs_sides', models.IntegerField(default=4)),
                ('medSprojs_count', models.IntegerField(default=0)),
                ('medSprojs_sides', models.IntegerField(default=4)),
                ('overhangda_count', models.IntegerField(default=0)),
                ('overhangda_sides', models.IntegerField(default=4)),
                ('balkong_count', models.IntegerField(default=0)),
                ('balkong_sides', models.IntegerField(default=4, verbose_name='Helt eller Endast glasräcke')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='flyttochren.fonsterputs')),
            ],
        ),
    ]
