# Generated by Django 5.0.4 on 2024-06-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyttochren', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flyttstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bostadsyta', models.CharField(blank=True, max_length=255)),
                ('keyStatus', models.CharField(choices=[('atHome', 'atHome'), ('willLeaveOneDayBefore', 'willLeaveOneDayBefore'), ('alreadyLeftKey', 'alreadyLeftKey')], default='atHome', max_length=50)),
                ('serviceAvgift', models.IntegerField(default=70)),
                ('totalAmount', models.IntegerField()),
                ('selectedDate', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('selectedTime', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Info För Storstädning', 'verbose_name_plural': 'User Info För Storstädning'},
        ),
        migrations.AlterModelOptions(
            name='userinfofonsterputs',
            options={'verbose_name': 'User Info För Fönsterputs', 'verbose_name_plural': 'User Info För Fönsterputs'},
        ),
        migrations.AlterModelOptions(
            name='userinfohemstadning',
            options={'verbose_name': 'User Info För Hemstädning', 'verbose_name_plural': 'User Info För Hemstädning'},
        ),
        migrations.AlterModelOptions(
            name='windows',
            options={'verbose_name': 'Windows För Storstädning', 'verbose_name_plural': 'Windows För Storstädning'},
        ),
        migrations.AlterModelOptions(
            name='windowsfonsterputs',
            options={'verbose_name': 'Windows För Fönsterputs', 'verbose_name_plural': 'Windows För Fönsterputs'},
        ),
        migrations.CreateModel(
            name='UserInfoFlyttstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('gatuAdress', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress')),
                ('postNummer', models.CharField(blank=True, max_length=10, verbose_name='Postnummer')),
                ('postOrt', models.CharField(blank=True, max_length=100, verbose_name='Post Ort')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='flyttochren.flyttstadning')),
            ],
            options={
                'verbose_name': 'User Info För Flyttstädning',
                'verbose_name_plural': 'User Info För Flyttstädning',
            },
        ),
    ]
