# Generated by Django 5.0.4 on 2024-06-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyttochren', '0002_flyttstadning_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
