# Generated by Django 5.0.4 on 2024-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyttochren', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontorsstadning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foretagsNamn', models.CharField(blank=True, max_length=100, verbose_name='FöretagsNamn')),
                ('orgNum', models.CharField(blank=True, max_length=100, verbose_name='Organisationsnummer')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('gatuAdress', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress')),
                ('postNummer', models.CharField(blank=True, max_length=10, verbose_name='Postnummer')),
                ('postOrt', models.CharField(blank=True, max_length=100, verbose_name='Post Ort')),
                ('kommentar', models.TextField(blank=True, verbose_name='kommentar')),
            ],
            options={
                'verbose_name': 'Kontorsstädning',
                'verbose_name_plural': 'Kontorsstädning',
            },
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Kontakt Form', 'verbose_name_plural': 'Kontakt Form'},
        ),
    ]
