# Generated by Django 5.0.4 on 2024-06-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyttochren', '0005_trapstadning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trapstadning',
            new_name='Trappstadning',
        ),
        migrations.AlterModelOptions(
            name='trappstadning',
            options={'verbose_name': 'Trappstädning', 'verbose_name_plural': 'Trappstädning'},
        ),
    ]
