# Generated by Django 5.0.4 on 2024-06-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyttochren', '0006_rename_trapstadning_trappstadning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flytt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnummerFrom', models.CharField(blank=True, max_length=10, verbose_name='Postnummer från')),
                ('cityFrom', models.CharField(blank=True, max_length=100, verbose_name='Stad från')),
                ('gatuAdressFrom', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress från')),
                ('boendeTypFrom', models.CharField(choices=[('villaRadhus', 'villaRadhus'), ('lagenhet', 'lagenhet'), ('forrad', 'forrad')], default='villaRadhus', max_length=50)),
                ('bostadsytaFrom', models.CharField(blank=True, max_length=255, verbose_name='Yta från')),
                ('biutrymmenFrom', models.CharField(blank=True, max_length=255, verbose_name='Biutrymmen från')),
                ('vaningFrom', models.CharField(blank=True, max_length=255, verbose_name='Våning från')),
                ('hissFrom', models.CharField(blank=True, max_length=255, verbose_name='Hiss från')),
                ('postnummerTo', models.CharField(blank=True, max_length=10, verbose_name='Postnummer till')),
                ('cityTo', models.CharField(blank=True, max_length=100, verbose_name='Stad till')),
                ('gatuAdressTo', models.CharField(blank=True, max_length=255, verbose_name='Gatu Adress till')),
                ('boendeTypTo', models.CharField(choices=[('villaRadhus2', 'villaRadhus2'), ('lagenhet2', 'lagenhet2'), ('forrad2', 'forrad2')], default='villaRadhus2', max_length=50)),
                ('bostadsytaTo', models.CharField(blank=True, max_length=255, verbose_name='Yta till')),
                ('biutrymmenTo', models.CharField(blank=True, max_length=255, verbose_name='Biutrymmen till')),
                ('vaningTo', models.CharField(blank=True, max_length=255, verbose_name='Våning till')),
                ('hissTo', models.CharField(blank=True, max_length=255, verbose_name='Hiss till')),
                ('kommentar', models.TextField(blank=True, verbose_name='kommentar')),
                ('hasNedpacking', models.BooleanField(default=False, verbose_name='Nedpacking')),
                ('hasUppacking', models.BooleanField(default=False, verbose_name='Uppacking')),
                ('hasMagasinering', models.BooleanField(default=False, verbose_name='Magasinering')),
                ('hasFlyttstad', models.BooleanField(default=False, verbose_name='Flyttstäd')),
                ('hasAtervinning', models.BooleanField(default=False, verbose_name='Återvinning')),
                ('selectedDate', models.DateField(blank=True, null=True, verbose_name='Flyttdatum')),
                ('selectedTime', models.TimeField(blank=True, null=True, verbose_name='Flytttid')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoFlytt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, verbose_name='Förnamn')),
                ('lastName', models.CharField(blank=True, max_length=100, verbose_name='Efternamn')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Epost')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='flyttochren.flytt')),
            ],
            options={
                'verbose_name': 'User Info För Flytt',
                'verbose_name_plural': 'User Info För Flytt',
            },
        ),
    ]
